// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBys0MhpRjW0xLi9pwNrzfVCSq-xQaRoMg',
    appId: '1:248877361095:android:45bb624c70b28e74',
    messagingSenderId: '248877361095',
    projectId: 'nest-app-5f1f5',
    databaseURL: 'https://nest-app-5f1f5.firebaseio.com',
    storageBucket: 'nest-app-5f1f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa8d3QINlLrLgByryS75nRh9IftEfDKlQ',
    appId: '1:248877361095:ios:cb6ad9449690fcf7c35be2',
    messagingSenderId: '248877361095',
    projectId: 'nest-app-5f1f5',
    databaseURL: 'https://nest-app-5f1f5.firebaseio.com',
    storageBucket: 'nest-app-5f1f5.appspot.com',
    iosClientId:
        '248877361095-at3538lupg1525bphuua84003uis7d7q.apps.googleusercontent.com',
    iosBundleId: 'com.wac.NestMatrimony',
  );
}
